[package]
name = "rustbox"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
poise = "0.6.1"
rand = "0.8.5"
strum = "0.26.2"
dotenv = "0.15.0"
strum_macros = "0.26.2"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }